name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      # BƯỚC NÀY ĐỂ XUẤT FILE .JAR CHO BẠN TẢI VỀ CÀI VÀO GAME
      - name: Upload Mod Jar
        uses: actions/upload-artifact@v4
        with:
          name: Dragon-Mounts-Mod
          path: build/libs/*.jar